
#include "ad7124.h"


// External driver structures and buffers
extern AD7124_ConfigTypeDef AD7124_Handler;
extern uint32_t AD7124_ChannelSamples[AD7124_ENABLED_CHANNELS];
extern AD7124_RegisterTypeDef configA;

// Status array for tracking return values from driver functions
AD7124_StatusTypeDef status[3U];

// Flag for DOUT/RDY interrupt
volatile uint8_t ad7124_rdy_flag = 0U;

// Variables for error status, voltage, and temperature calculation
int32_t ad7124_error = 0U;
double voltage;
float temperature;


int main(void)
{
    
    /* Initialize HAL, system clock, GPIOs, SPI, and EXTI (generated by STM32CubeMX) */
    // HAL_Init();
    // SystemClock_Config();
    // MX_GPIO_Init();
    // MX_SPI2_Init();
    // etc...
    

    
    /* Configure AD7124 handler structure */
    AD7124_Handler.SPIx = &hspi2;        // SPI peripheral used
    AD7124_Handler.csPort = GPIOB;       // GPIO port for CS
    AD7124_Handler.csPin = GPIO_PIN_12;  // GPIO pin for CS
    AD7124_Handler.IRQn = EXTI9_5_IRQn;  // External interrupt line connected to DOUT/RDY
	
    HAL_NVIC_DisableIRQ(AD7124_Handler.IRQn);  // Disable IRQ during initial config
    status[0U] = AD7124_Config(&AD7124_Handler, &configA);  // Initialize and configure the AD7124
    HAL_NVIC_EnableIRQ(AD7124_Handler.IRQn);   // Re-enable interrupt after initialization
    
    
    while (1)
    {       
        /* Check if data is ready (set in external interrupt) */
        if (ad7124_rdy_flag)
        {
            HAL_NVIC_DisableIRQ(AD7124_Handler.IRQn);  // Temporarily disable interrupt
            
            /* Optional: check for errors */
            status[1U] = AD7124_ErrorCheck(&AD7124_Handler, &ad7124_error);
            
            /* Read conversion results from ADC */
            status[2U] = AD7124_ReadSampleData(&AD7124_Handler);
            
            /* Process raw ADC values if available */
            if (AD7124_ChannelSamples[0] && AD7124_ChannelSamples[1])
            {
                // Convert raw ADC data from channel 0 to millivolts (example scaling)
                voltage = ( ( (double)(AD7124_ChannelSamples[0U] / 8388608.0) - 1.0) * 2.5) * 1000.0;
                
                // Convert raw ADC data from channel 1 to temperature in °C
                temperature = ( (AD7124_ChannelSamples[1U] - 8388608.0) / 13548.0) - 272.5;
            }
            
            ad7124_rdy_flag = 0U;                     // Clear ready flag
            HAL_NVIC_EnableIRQ(AD7124_Handler.IRQn);  // Re-enable interrupt
        }
           
        // Your other application code here       
    }   
}
