################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32WBxx_HAL_Driver/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/DFU/Src \
Middlewares/ST/STM32_USB_Device_Library/Core/Src \
Middlewares/ST/STM32_WPAN/ble/core/auto \
Middlewares/ST/STM32_WPAN/ble/core/template \
Middlewares/ST/STM32_WPAN/ble/svc/Src \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl \
Middlewares/ST/STM32_WPAN/utilities \
STM32_WPAN/App \
STM32_WPAN/Target \
USB_Device/App \
USB_Device/Target \
Utilities/lpm/tiny_lpm \
Utilities/sequencer \
lvgl/demos/benchmark/assets \
lvgl/demos/benchmark \
lvgl/demos/gltf \
lvgl/demos/keypad_encoder \
lvgl/demos \
lvgl/demos/music/assets \
lvgl/demos/music \
lvgl/demos/render/assets \
lvgl/demos/render \
lvgl/demos/stress \
lvgl/demos/vector_graphic/assets \
lvgl/demos/vector_graphic \
lvgl/demos/widgets/assets \
lvgl/demos/widgets \
lvgl/examples/anim \
lvgl/examples/assets \
lvgl/examples/assets/emoji \
lvgl/examples/event \
lvgl/examples/get_started \
lvgl/examples/grad \
lvgl/examples/layouts/flex \
lvgl/examples/layouts/grid \
lvgl/examples/libs/barcode \
lvgl/examples/libs/bmp \
lvgl/examples/libs/ffmpeg \
lvgl/examples/libs/freetype \
lvgl/examples/libs/gif \
lvgl/examples/libs/gltf \
lvgl/examples/libs/gstreamer \
lvgl/examples/libs/libjpeg_turbo \
lvgl/examples/libs/libpng \
lvgl/examples/libs/lodepng \
lvgl/examples/libs/qrcode \
lvgl/examples/libs/rlottie \
lvgl/examples/libs/svg \
lvgl/examples/libs/tiny_ttf \
lvgl/examples/libs/tjpgd \
lvgl/examples/others/file_explorer \
lvgl/examples/others/font_manager \
lvgl/examples/others/fragment \
lvgl/examples/others/gestures \
lvgl/examples/others/gridnav \
lvgl/examples/others/ime \
lvgl/examples/others/imgfont \
lvgl/examples/others/monkey \
lvgl/examples/others/observer \
lvgl/examples/others/snapshot \
lvgl/examples/others/translation \
lvgl/examples/others/xml \
lvgl/examples/porting \
lvgl/examples/porting/osal \
lvgl/examples/scroll \
lvgl/examples/styles \
lvgl/examples/widgets/animimg \
lvgl/examples/widgets/arc \
lvgl/examples/widgets/arclabel \
lvgl/examples/widgets/bar \
lvgl/examples/widgets/button \
lvgl/examples/widgets/buttonmatrix \
lvgl/examples/widgets/calendar \
lvgl/examples/widgets/canvas \
lvgl/examples/widgets/chart \
lvgl/examples/widgets/checkbox \
lvgl/examples/widgets/dropdown \
lvgl/examples/widgets/image \
lvgl/examples/widgets/imagebutton \
lvgl/examples/widgets/keyboard \
lvgl/examples/widgets/label \
lvgl/examples/widgets/led \
lvgl/examples/widgets/line \
lvgl/examples/widgets/list \
lvgl/examples/widgets/lottie \
lvgl/examples/widgets/menu \
lvgl/examples/widgets/msgbox \
lvgl/examples/widgets/obj \
lvgl/examples/widgets/roller \
lvgl/examples/widgets/scale \
lvgl/examples/widgets/slider \
lvgl/examples/widgets/span \
lvgl/examples/widgets/spinbox \
lvgl/examples/widgets/spinner \
lvgl/examples/widgets/switch \
lvgl/examples/widgets/table \
lvgl/examples/widgets/tabview \
lvgl/examples/widgets/textarea \
lvgl/examples/widgets/tileview \
lvgl/examples/widgets/win \

