################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
AD7124_Library \
AD7124_Library/examples/ad7124-cn0381 \
Adafruit_1704X_Library \
Adafruit_MAX31856_Library \
Core/Src \
Core/Startup \
Drivers/STM32WBxx_HAL_Driver/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/DFU/Src \
Middlewares/ST/STM32_USB_Device_Library/Core/Src \
Middlewares/ST/STM32_WPAN/ble/core/auto \
Middlewares/ST/STM32_WPAN/ble/core/template \
Middlewares/ST/STM32_WPAN/ble/svc/Src \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl \
Middlewares/ST/STM32_WPAN/utilities \
STM32_WPAN/App \
STM32_WPAN/Target \
USB_Device/App \
USB_Device/Target \
Utilities/lpm/tiny_lpm \
Utilities/sequencer \
lvgl/demos/benchmark/assets \
lvgl/demos/benchmark \
lvgl/demos/gltf \
lvgl/demos/keypad_encoder \
lvgl/demos \
lvgl/demos/music/assets \
lvgl/demos/music \
lvgl/demos/render/assets \
lvgl/demos/render \
lvgl/demos/stress \
lvgl/demos/vector_graphic/assets \
lvgl/demos/vector_graphic \
lvgl/demos/widgets/assets \
lvgl/demos/widgets \
lvgl/env_support/pikascript \
lvgl/env_support/rt-thread \
lvgl/env_support/rt-thread/squareline \
lvgl/examples/anim \
lvgl/examples/assets \
lvgl/examples/assets/emoji \
lvgl/examples/event \
lvgl/examples/get_started \
lvgl/examples/grad \
lvgl/examples/layouts/flex \
lvgl/examples/layouts/grid \
lvgl/examples/libs/barcode \
lvgl/examples/libs/bmp \
lvgl/examples/libs/ffmpeg \
lvgl/examples/libs/freetype \
lvgl/examples/libs/gif \
lvgl/examples/libs/gltf \
lvgl/examples/libs/gstreamer \
lvgl/examples/libs/libjpeg_turbo \
lvgl/examples/libs/libpng \
lvgl/examples/libs/lodepng \
lvgl/examples/libs/qrcode \
lvgl/examples/libs/rlottie \
lvgl/examples/libs/svg \
lvgl/examples/libs/tiny_ttf \
lvgl/examples/libs/tjpgd \
lvgl/examples/others/file_explorer \
lvgl/examples/others/font_manager \
lvgl/examples/others/fragment \
lvgl/examples/others/gestures \
lvgl/examples/others/gridnav \
lvgl/examples/others/ime \
lvgl/examples/others/imgfont \
lvgl/examples/others/monkey \
lvgl/examples/others/observer \
lvgl/examples/others/snapshot \
lvgl/examples/others/translation \
lvgl/examples/others/xml \
lvgl/examples/porting \
lvgl/examples/porting/osal \
lvgl/examples/scroll \
lvgl/examples/styles \
lvgl/examples/widgets/animimg \
lvgl/examples/widgets/arc \
lvgl/examples/widgets/arclabel \
lvgl/examples/widgets/bar \
lvgl/examples/widgets/button \
lvgl/examples/widgets/buttonmatrix \
lvgl/examples/widgets/calendar \
lvgl/examples/widgets/canvas \
lvgl/examples/widgets/chart \
lvgl/examples/widgets/checkbox \
lvgl/examples/widgets/dropdown \
lvgl/examples/widgets/image \
lvgl/examples/widgets/imagebutton \
lvgl/examples/widgets/keyboard \
lvgl/examples/widgets/label \
lvgl/examples/widgets/led \
lvgl/examples/widgets/line \
lvgl/examples/widgets/list \
lvgl/examples/widgets/lottie \
lvgl/examples/widgets/menu \
lvgl/examples/widgets/msgbox \
lvgl/examples/widgets/obj \
lvgl/examples/widgets/roller \
lvgl/examples/widgets/scale \
lvgl/examples/widgets/slider \
lvgl/examples/widgets/span \
lvgl/examples/widgets/spinbox \
lvgl/examples/widgets/spinner \
lvgl/examples/widgets/switch \
lvgl/examples/widgets/table \
lvgl/examples/widgets/tabview \
lvgl/examples/widgets/textarea \
lvgl/examples/widgets/tileview \
lvgl/examples/widgets/win \
lvgl/src/core \
lvgl/src/display \
lvgl/src/draw/convert/helium \
lvgl/src/draw/convert \
lvgl/src/draw/convert/neon \
lvgl/src/draw/dma2d \
lvgl/src/draw/espressif/ppa \
lvgl/src/draw/eve \
lvgl/src/draw \
lvgl/src/draw/nema_gfx \
lvgl/src/draw/nxp/g2d \
lvgl/src/draw/nxp/pxp \
lvgl/src/draw/opengles \
lvgl/src/draw/renesas/dave2d \
lvgl/src/draw/sdl \
lvgl/src/draw/sw/blend/helium \
lvgl/src/draw/sw/blend \
lvgl/src/draw/sw/blend/neon \
lvgl/src/draw/sw \
lvgl/src/draw/vg_lite \
lvgl/src/drivers/display/drm \
lvgl/src/drivers/display/fb \
lvgl/src/drivers/display/ft81x \
lvgl/src/drivers/display/ili9341 \
lvgl/src/drivers/display/lcd \
lvgl/src/drivers/display/lovyan_gfx \
lvgl/src/drivers/display/nxp_elcdif \
lvgl/src/drivers/display/renesas_glcdc \
lvgl/src/drivers/display/st7735 \
lvgl/src/drivers/display/st7789 \
lvgl/src/drivers/display/st7796 \
lvgl/src/drivers/display/st_ltdc \
lvgl/src/drivers/display/tft_espi \
lvgl/src/drivers/draw/eve \
lvgl/src/drivers/evdev \
lvgl/src/drivers/libinput \
lvgl/src/drivers/nuttx \
lvgl/src/drivers/opengles/assets \
lvgl/src/drivers/opengles/glad/src \
lvgl/src/drivers/opengles \
lvgl/src/drivers/opengles/opengl_shader \
lvgl/src/drivers/qnx \
lvgl/src/drivers/sdl \
lvgl/src/drivers/uefi \
lvgl/src/drivers/wayland \
lvgl/src/drivers/windows \
lvgl/src/drivers/x11 \
lvgl/src/font \
lvgl/src/indev \
lvgl/src/layouts/flex \
lvgl/src/layouts/grid \
lvgl/src/layouts \
lvgl/src/libs/FT800-FT813 \
lvgl/src/libs/barcode \
lvgl/src/libs/bin_decoder \
lvgl/src/libs/bmp \
lvgl/src/libs/expat \
lvgl/src/libs/ffmpeg \
lvgl/src/libs/freetype \
lvgl/src/libs/frogfs/src \
lvgl/src/libs/fsdrv \
lvgl/src/libs/gif/AnimatedGIF/src \
lvgl/src/libs/gif \
lvgl/src/libs/gltf/gltf_data \
lvgl/src/libs/gltf/gltf_view/assets \
lvgl/src/libs/gltf/gltf_view/ibl \
lvgl/src/libs/gltf/gltf_view \
lvgl/src/libs/gltf/math \
lvgl/src/libs/gstreamer \
lvgl/src/libs/libjpeg_turbo \
lvgl/src/libs/libpng \
lvgl/src/libs/lodepng \
lvgl/src/libs/lz4 \
lvgl/src/libs/qrcode \
lvgl/src/libs/rle \
lvgl/src/libs/rlottie \
lvgl/src/libs/svg \
lvgl/src/libs/thorvg \
lvgl/src/libs/tiny_ttf \
lvgl/src/libs/tjpgd \
lvgl/src/libs/vg_lite_driver/VGLite \
lvgl/src/libs/vg_lite_driver/VGLiteKernel \
lvgl/src/libs/vg_lite_driver/lv_vg_lite_hal \
lvgl/src \
lvgl/src/misc/cache/class \
lvgl/src/misc/cache/instance \
lvgl/src/misc/cache \
lvgl/src/misc \
lvgl/src/osal \
lvgl/src/others/file_explorer \
lvgl/src/others/font_manager \
lvgl/src/others/fragment \
lvgl/src/others/gridnav \
lvgl/src/others/ime \
lvgl/src/others/imgfont \
lvgl/src/others/monkey \
lvgl/src/others/observer \
lvgl/src/others/snapshot \
lvgl/src/others/sysmon \
lvgl/src/others/test \
lvgl/src/others/translation \
lvgl/src/others/vg_lite_tvg \
lvgl/src/others/xml \
lvgl/src/others/xml/parsers \
lvgl/src/stdlib/builtin \
lvgl/src/stdlib/clib \
lvgl/src/stdlib \
lvgl/src/stdlib/micropython \
lvgl/src/stdlib/rtthread \
lvgl/src/stdlib/uefi \
lvgl/src/themes/default \
lvgl/src/themes \
lvgl/src/themes/mono \
lvgl/src/themes/simple \
lvgl/src/tick \
lvgl/src/widgets/3dtexture \
lvgl/src/widgets/animimage \
lvgl/src/widgets/arc \
lvgl/src/widgets/arclabel \
lvgl/src/widgets/bar \
lvgl/src/widgets/button \
lvgl/src/widgets/buttonmatrix \
lvgl/src/widgets/calendar \
lvgl/src/widgets/canvas \
lvgl/src/widgets/chart \
lvgl/src/widgets/checkbox \
lvgl/src/widgets/dropdown \
lvgl/src/widgets/image \
lvgl/src/widgets/imagebutton \
lvgl/src/widgets/keyboard \
lvgl/src/widgets/label \
lvgl/src/widgets/led \
lvgl/src/widgets/line \
lvgl/src/widgets/list \
lvgl/src/widgets/lottie \
lvgl/src/widgets/menu \
lvgl/src/widgets/msgbox \
lvgl/src/widgets/objx_templ \
lvgl/src/widgets/property \
lvgl/src/widgets/roller \
lvgl/src/widgets/scale \
lvgl/src/widgets/slider \
lvgl/src/widgets/span \
lvgl/src/widgets/spinbox \
lvgl/src/widgets/spinner \
lvgl/src/widgets/switch \
lvgl/src/widgets/table \
lvgl/src/widgets/tabview \
lvgl/src/widgets/textarea \
lvgl/src/widgets/tileview \
lvgl/src/widgets/win \

